<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Ellie Grace Moore" />

<meta name="date" content="2022-03-29" />

<title>Lab 04 - Whole Game</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">This is an example!</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="analysis.html">Analysis</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/elliegr">
    <span class="fa fa-heart"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lab 04 - Whole Game</h1>
<h4 class="author">Ellie Grace Moore</h4>
<h4 class="date">2022-03-29</h4>

</div>


<div id="the-causal-question" class="section level2">
<h2>The Causal Question</h2>
<p>We are working with the <code>nhefs</code> (National Health and Nutrition Examination Survey) data set which contains 1629 observations of 67 variables. The variables in this dataset mostly relate to an individual’s health with a few involving tobacco prices and tax. We are interested in the effect of quitting smoking on ones weight. More specifically: <strong>with ones weight in 1971 as the starting point, does quitting smoking between the years 1971-1982 influence ones weight in 1982?</strong> For this question, we are interested in estimating the average treatment effect for the overall population. The variables we are particularly interested in are:</p>
<ul>
<li><strong>wt71</strong>: weight in kilograms in 1971</li>
<li><strong>age</strong>: age in 1971</li>
<li><strong>sex</strong>: 0: male with 1: female</li>
<li><strong>smokeyrs</strong>: years of smoking</li>
<li><strong>exercise</strong>: In recreation, how much do you exercise? In 1971, 0:much exercise, 1:moderate exercise, 2:little or no exercise</li>
<li><strong>alcoholfreq</strong>: How often do you drink? In 1971 0: Almost every day, 1: 2-3 times/week, 2: 1-4 times/month, 3: &lt; 12 times/year, 4: No alcohol last year, 5: Unknown</li>
<li><strong>ht</strong>: heigh in cm in 1971</li>
<li><strong>income</strong>: Total family income in 1971 11:&lt;$1000, 12: 1000-1999, 13: 2000-2999, 14: 3000-3999, 15: 4000-4999, 16: 5000-5999, 17: 6000-6999, 18: 7000-9999, 19: 10000-14999, 20: 15000-19999, 21: 20000-24999, 22: 25000+</li>
<li><strong>marital</strong>: Marital status in 1971 1: Under 17, 2: Married, 3: Widowed, 4: Never married, 5: Divorced, 6: Separated, 8: Unknown</li>
<li><strong>qsmk</strong> (exposure): quit smoking between 1st questionnaire and 1982, 1: Yes, 0: No</li>
<li><strong>wt82</strong> (outcome): weight in kilograms in 1982</li>
</ul>
<p>We start by making a table that shows more about how each of our variables are distributed.</p>
<pre class="r"><code>nhefs %&gt;%
  tbl_summary(
    by = qsmk, 
    include = c( 
                &quot;wt71&quot;,
                &quot;age&quot;,
                &quot;sex&quot;,
                &quot;smokeyrs&quot;,
                &quot;exercise&quot;,
                &quot;alcoholfreq&quot;,
                &quot;ht&quot;,
                &quot;income&quot;,
                &quot;marital&quot;,
                &quot;qsmk&quot;,
                &quot;wt82&quot;)) %&gt;%
  add_overall()</code></pre>
<div id="tapjgfacwh" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#tapjgfacwh .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#tapjgfacwh .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#tapjgfacwh .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#tapjgfacwh .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#tapjgfacwh .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tapjgfacwh .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#tapjgfacwh .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#tapjgfacwh .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#tapjgfacwh .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#tapjgfacwh .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#tapjgfacwh .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#tapjgfacwh .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#tapjgfacwh .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#tapjgfacwh .gt_from_md > :first-child {
  margin-top: 0;
}

#tapjgfacwh .gt_from_md > :last-child {
  margin-bottom: 0;
}

#tapjgfacwh .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#tapjgfacwh .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#tapjgfacwh .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#tapjgfacwh .gt_row_group_first td {
  border-top-width: 2px;
}

#tapjgfacwh .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#tapjgfacwh .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#tapjgfacwh .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#tapjgfacwh .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tapjgfacwh .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#tapjgfacwh .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#tapjgfacwh .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#tapjgfacwh .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tapjgfacwh .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#tapjgfacwh .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#tapjgfacwh .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#tapjgfacwh .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#tapjgfacwh .gt_left {
  text-align: left;
}

#tapjgfacwh .gt_center {
  text-align: center;
}

#tapjgfacwh .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#tapjgfacwh .gt_font_normal {
  font-weight: normal;
}

#tapjgfacwh .gt_font_bold {
  font-weight: bold;
}

#tapjgfacwh .gt_font_italic {
  font-style: italic;
}

#tapjgfacwh .gt_super {
  font-size: 65%;
}

#tapjgfacwh .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#tapjgfacwh .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#tapjgfacwh .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#tapjgfacwh .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#tapjgfacwh .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Overall</strong>, N = 1,566<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>0</strong>, N = 1,163<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>1</strong>, N = 403<sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">WEIGHT IN KILOGRAMS  IN 1971</td>
<td class="gt_row gt_center">69 (60, 80)</td>
<td class="gt_row gt_center">68 (59, 79)</td>
<td class="gt_row gt_center">71 (61, 81)</td></tr>
    <tr><td class="gt_row gt_left">AGE IN 1971</td>
<td class="gt_row gt_center">43 (33, 53)</td>
<td class="gt_row gt_center">42 (33, 51)</td>
<td class="gt_row gt_center">46 (35, 56)</td></tr>
    <tr><td class="gt_row gt_left">0: MALE 1: FEMALE</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">0</td>
<td class="gt_row gt_center">762 (49%)</td>
<td class="gt_row gt_center">542 (47%)</td>
<td class="gt_row gt_center">220 (55%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">1</td>
<td class="gt_row gt_center">804 (51%)</td>
<td class="gt_row gt_center">621 (53%)</td>
<td class="gt_row gt_center">183 (45%)</td></tr>
    <tr><td class="gt_row gt_left">YEARS OF SMOKING</td>
<td class="gt_row gt_center">24 (15, 33)</td>
<td class="gt_row gt_center">23 (15, 32)</td>
<td class="gt_row gt_center">26 (15, 35)</td></tr>
    <tr><td class="gt_row gt_left">IN RECREATION, HOW MUCH EXERCISE? IN 1971, 0:much exercise,1:moderate exercise,2:little or no exercise</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">0</td>
<td class="gt_row gt_center">300 (19%)</td>
<td class="gt_row gt_center">237 (20%)</td>
<td class="gt_row gt_center">63 (16%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">1</td>
<td class="gt_row gt_center">661 (42%)</td>
<td class="gt_row gt_center">485 (42%)</td>
<td class="gt_row gt_center">176 (44%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">2</td>
<td class="gt_row gt_center">605 (39%)</td>
<td class="gt_row gt_center">441 (38%)</td>
<td class="gt_row gt_center">164 (41%)</td></tr>
    <tr><td class="gt_row gt_left">HOW OFTEN DO YOU DRINK?  IN 1971  0: Almost every day, 1: 2-3 times/week, 2: 1-4 times/month, 3: &lt; 12 times/year, 4: No alcohol last year, 5: Unknown</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">0</td>
<td class="gt_row gt_center">325 (21%)</td>
<td class="gt_row gt_center">242 (21%)</td>
<td class="gt_row gt_center">83 (21%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">1</td>
<td class="gt_row gt_center">219 (14%)</td>
<td class="gt_row gt_center">171 (15%)</td>
<td class="gt_row gt_center">48 (12%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">2</td>
<td class="gt_row gt_center">494 (32%)</td>
<td class="gt_row gt_center">359 (31%)</td>
<td class="gt_row gt_center">135 (33%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">3</td>
<td class="gt_row gt_center">328 (21%)</td>
<td class="gt_row gt_center">249 (21%)</td>
<td class="gt_row gt_center">79 (20%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">4</td>
<td class="gt_row gt_center">195 (12%)</td>
<td class="gt_row gt_center">138 (12%)</td>
<td class="gt_row gt_center">57 (14%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">5</td>
<td class="gt_row gt_center">5 (0.3%)</td>
<td class="gt_row gt_center">4 (0.3%)</td>
<td class="gt_row gt_center">1 (0.2%)</td></tr>
    <tr><td class="gt_row gt_left">HEIGHT IN CENTIMETERS IN 1971</td>
<td class="gt_row gt_center">168 (162, 175)</td>
<td class="gt_row gt_center">168 (162, 175)</td>
<td class="gt_row gt_center">169 (162, 176)</td></tr>
    <tr><td class="gt_row gt_left">TOTAL FAMILY INCOME IN 1971  11:&lt;$1000, 12: 1000-1999, 13: 2000-2999, 14: 3000-3999, 15: 4000-4999, 16: 5000-5999, 17: 6000-6999, 18: 7000-9999, 19: 10000-14999, 20: 15000-19999, 21: 20000-24999, 22: 25000+</td>
<td class="gt_row gt_center">19.0 (17.0, 20.0)</td>
<td class="gt_row gt_center">19.0 (16.8, 20.0)</td>
<td class="gt_row gt_center">19.0 (18.0, 20.0)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Unknown</td>
<td class="gt_row gt_center">59</td>
<td class="gt_row gt_center">35</td>
<td class="gt_row gt_center">24</td></tr>
    <tr><td class="gt_row gt_left">MARITAL STATUS IN 1971  1: Under 17, 2: Married, 3: Widowed, 4: Never married, 5: Divorced, 6: Separated, 8: Unknown</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">2</td>
<td class="gt_row gt_center">1,237 (79%)</td>
<td class="gt_row gt_center">906 (78%)</td>
<td class="gt_row gt_center">331 (82%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">3</td>
<td class="gt_row gt_center">88 (5.6%)</td>
<td class="gt_row gt_center">64 (5.5%)</td>
<td class="gt_row gt_center">24 (6.0%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">4</td>
<td class="gt_row gt_center">93 (5.9%)</td>
<td class="gt_row gt_center">74 (6.4%)</td>
<td class="gt_row gt_center">19 (4.7%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">5</td>
<td class="gt_row gt_center">92 (5.9%)</td>
<td class="gt_row gt_center">74 (6.4%)</td>
<td class="gt_row gt_center">18 (4.5%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">6</td>
<td class="gt_row gt_center">55 (3.5%)</td>
<td class="gt_row gt_center">45 (3.9%)</td>
<td class="gt_row gt_center">10 (2.5%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">8</td>
<td class="gt_row gt_center">1 (&lt;0.1%)</td>
<td class="gt_row gt_center">0 (0%)</td>
<td class="gt_row gt_center">1 (0.2%)</td></tr>
    <tr><td class="gt_row gt_left">WEIGHT IN KILOGRAMS  IN 1982</td>
<td class="gt_row gt_center">72 (62, 83)</td>
<td class="gt_row gt_center">70 (61, 82)</td>
<td class="gt_row gt_center">75 (64, 86)</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><sup class="gt_footnote_marks">1</sup> Median (IQR); n (%)</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
<div id="missing-data" class="section level2">
<h2>Missing Data</h2>
<p>Before we can begin our causal assessment, we must investigate any missing data. To do this, we create a plot that helps us visualize any missing data:</p>
<pre class="r"><code>nhefs %&gt;% 
  select(sex, age, smokeyrs, wt71, wt82, marital, ht, alcoholfreq, exercise, income) %&gt;% vis_dat(palette = &quot;cb_safe&quot;) +
  ggtitle(&quot;Visualizing Missing Data&quot;)</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-4-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>It appears that the only variables that has missing values is income. With this being said, we will conduct a predictive mean matching imputation method in order to impute these missing values. We also recreate the above plot to ensure that there are no longer missing data.</p>
<pre class="r"><code>nhefs_imp &lt;- mice(nhefs, m = 1, method = &quot;pmm&quot;, printFlag = FALSE) #single imputation
complete_data &lt;- complete(nhefs_imp)

complete_data %&gt;% 
   select(sex, age, smokeyrs, wt71, wt82, marital, ht, alcoholfreq, exercise, income) %&gt;% vis_dat(palette = &quot;cb_safe&quot;) + 
  ggtitle(&quot;Visualizing Missing Data&quot;, subtitle = &quot;(There is none!)&quot;)</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-5-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="proposed-dag" class="section level2">
<h2>Proposed DAG</h2>
<p>We now have a complete dataset. To begin, we specify relationships for our exposure and outcome along with the other variables. Our proposed DAG is below.</p>
<pre class="r"><code>dag &lt;- dagify(
wt82 ~ wt71 + sex + age + exercise + ht + alcoholfreq + income,
qsmk ~ age + sex + smokeyrs + alcoholfreq + exercise + marital + income, 
  exposure = &quot;qsmk&quot;, 
  outcome = &quot;wt82&quot;
) 
dag %&gt;%
  ggdag() + 
  geom_dag_node(color = &quot;plum4&quot;) + 
  geom_dag_text(color = &quot;black&quot;) +
  theme_dag() </code></pre>
<p><img src="analysis_files/figure-html/dag-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>To prevent confounders, we need to close the backdoor paths on our DAG. To do this, we establish the adjustment set and adjust for those specified variables.</p>
<pre class="r"><code>dag %&gt;%
  ggdag_adjustment_set(stylized = TRUE) +
  geom_dag_text(color = &quot;black&quot;) +
  scale_color_manual(values = c(&quot;deeppink2&quot;, &quot;plum4&quot;)) +
  theme_minimal()</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>From the figure above, we can see that we need to adjust for age, alcoholfreq, exercise, income, and sex. These will therefore be the variables we include in our propensity score model.</p>
</div>
<div id="propensity-score-model" class="section level2">
<h2>Propensity Score Model</h2>
<p>We adjust for the above-listed variables by using a binomial model for our propensity scores. After specifying our model, we create a mirrored histogram of the calculatede propensity scores for both quitting and not quitting smoking.</p>
<pre class="r"><code>complete_data &lt;- 
  glm(qsmk ~ age + sex + income + exercise + alcoholfreq,
    data = complete_data,
    family = binomial()) %&gt;%
  augment(type.predict = &quot;response&quot;, data = complete_data) 

df_plot_ps &lt;- complete_data %&gt;%
  tidyr::pivot_wider(names_from = qsmk, 
                     values_from = .fitted, 
                     names_prefix = &quot;qsmk_p&quot;)

ggplot(df_plot_ps) +
  geom_histogram(bins = 50, 
                 aes(x = qsmk_p1), 
                 fill = &quot;deeppink2&quot;) + 
  geom_histogram(bins = 50, 
                 aes(x = qsmk_p0, 
                     y = - stat(count)), 
                 fill = &quot;plum4&quot;) + 
  
  scale_y_continuous(&quot;count&quot;, label = abs) + 
  scale_x_continuous(&quot;propensity score&quot;) +
  annotate(geom = &quot;label&quot;,
           x = 0.25,
           y= 5,
           label = &quot;Quit Smoking&quot;) + 
annotate(geom = &quot;label&quot;,
         x = 0.25,
         y = -5,
         label  = &quot;Didn&#39;t Quit Smoking&quot;) +
  ggtitle(&quot;Distribution of Unweighted Propensity Scores&quot;) +
  theme_minimal()</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;" /> The first observation we can make is that most people did not quit smoking. Also, we notice that those who did not quit smoking all had a relatively low probability for quitting, so the model did a good job here. However, for those who did quit smoking, there is more of a range of probabilities with a huddle around 0.2-0.3 range. We will now create a <em>weighted</em> mirrored histogram using weights for the average treatment effect.</p>
<pre class="r"><code>complete_data &lt;- complete_data %&gt;%
  mutate( 
    w_ate = qsmk / .fitted + 
      (1 - qsmk) / (1 - .fitted)
  )

df_plot_ps &lt;- complete_data %&gt;%
  tidyr::pivot_wider(names_from = qsmk, 
                     values_from = .fitted, 
                     names_prefix = &quot;qsmk_p&quot;)

ggplot(df_plot_ps) +
  geom_histogram(bins = 50,
                 aes(x = qsmk_p1), 
                 fill = &quot;deeppink2&quot;) + 
  geom_histogram(bins = 50, 
                 aes(x = qsmk_p1,
                     weight = w_ate), 
                 fill = &quot;deeppink2&quot;,
                 alpha = 0.5) +

  geom_histogram(bins = 50, 
                 aes(x = qsmk_p0, 
                     y = - stat(count)),
                 fill = &quot;plum4&quot;) + 
  geom_histogram(bins = 50,
                 aes(x = qsmk_p0, 
                     weight = w_ate, 
                     y = - stat(count)), 
                 fill = &quot;plum4&quot;,
                 alpha = 0.5) + 
  
  scale_y_continuous(&quot;Count&quot;, label = abs) + 
  scale_x_continuous(&quot;Propensity Score&quot;) +
  annotate(geom = &quot;label&quot;,
           x = 0.25,
           y= 5,
           label = &quot;Quit Smoking&quot;) +
annotate(geom = &quot;label&quot;,
         x = 0.25,
         y = -10,
         label  = &quot;Didn&#39;t Quit Smoking&quot;) + 
  ggtitle(&quot;Distribution of Weighted/Unweighted Propensity Scores&quot;) + 
  theme_minimal()</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" /></p>
<div id="checking-the-model" class="section level3">
<h3>Checking the Model</h3>
<p>We will now look at scaled mean differences (smd’s) and empirical CDF’s in order to determine if we need to reiterate our model with any polynomial or spline terms. We begin by looking at a love plot that shows the smd’s for each variable.</p>
<pre class="r"><code>smds &lt;- complete_data %&gt;%
  summarize(
    across(c(age, sex, exercise, alcoholfreq, income),
           list(unweighted = ~smd(.x, qsmk)$estimate,
                ate.weighted = ~smd(.x, qsmk, w = w_ate)$estimate))
  )

plot_df &lt;- smds %&gt;%
  pivot_longer(
    everything(),
    values_to = &quot;SMD&quot;,
    names_to = c(&quot;Variable&quot;, &quot;Method&quot;),
    names_pattern = &quot;(.*)_(.*)&quot;
  ) %&gt;%
  arrange(Method, abs(SMD)) %&gt;%
  mutate(Variable = fct_inorder(Variable))

ggplot(
  data = plot_df,
  aes(x = abs(SMD), y = Variable, 
      group = Method, color = Method)
) +  
  geom_line(orientation = &quot;y&quot;) +
  geom_point() + 
  geom_vline(xintercept = 0.1, 
             color = &quot;black&quot;, size = 0.1) +
  ggtitle(&quot;Love Plot for Sex, Age, Income, and Job&quot;) + 
  scale_color_manual(values = c(&quot;deeppink2&quot;, &quot;plum4&quot;)) + 
  theme_minimal()</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-9-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>According to this plot, changes to our propensity score model are not necessary since each scaled mean difference is below the specified value of 0.1. Next we look at an unweighted eCDF for age (since it is the only continuous variable).</p>
<pre class="r"><code>ggplot(complete_data, 
       aes(x = age, group = qsmk, 
           color = factor(qsmk))) +
  stat_ecdf() +
  scale_color_manual(&quot;Quit smoking&quot;, 
                     values = c(&quot;plum4&quot;, &quot;deeppink2&quot;),
                     labels = c(&quot;No&quot;, &quot;Yes&quot;)) + 
  scale_x_continuous(&quot;Age&quot;) + 
  ylab(&quot;Proportion &lt;= x&quot;) + 
  ggtitle(&quot;Unweighted eCDF for Age&quot;) +
  theme_minimal()</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>This eCDF is not bad, however the distributions could line up better in the middle. Let us now create a <strong>weighted</strong> eCDF (again, with our ATE weights) to see if we can get these to line up better.</p>
<pre class="r"><code>ecdf_1 &lt;- complete_data %&gt;%
  filter(qsmk == 1) %&gt;%
  arrange(age) %&gt;%
  mutate(cum_pct = cumsum(w_ate) / sum(w_ate))

ecdf_0 &lt;- complete_data %&gt;%
  filter(qsmk == 0) %&gt;%
  arrange(age) %&gt;%
  mutate(cum_pct = cumsum(w_ate) / sum(w_ate))

ggplot(ecdf_1, aes(x = age, y = cum_pct)) +
  geom_line(color = &quot;deeppink2&quot;) +
  geom_line(data = ecdf_0, 
            aes(x = age, y = cum_pct), 
            color = &quot;plum4&quot;) + 
  xlab(&quot;Age&quot;) + 
  ylab(&quot;Proportion &lt;= x&quot;) + 
  ggtitle(&quot;Age after ATE Weighting&quot;) +
annotate(geom = &quot;label&quot;,
         x = 45,
         y = 0.8,
         color = &quot;plum4&quot;,
         label = &quot;Didn&#39;t Quit Smoking&quot;) +
annotate(geom = &quot;label&quot;,
         x = 33,
         y = 0.4,
         color = &quot;deeppink2&quot;,
         label = &quot;Quit Smoking&quot;) +
  theme_minimal()</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>This weighted eCDF looks much better! After looking at the love plot and weighted eCDF, we can conclude that we do not need to iterate our propensity score model.</p>
</div>
</div>
<div id="the-effect" class="section level2">
<h2>The Effect</h2>
<pre class="r"><code>ATE &lt;- complete_data %&gt;% 
  summarise((sum(qsmk*wt82*w_ate)/sum(qsmk*w_ate))-(sum((1-qsmk)*wt82*w_ate)/sum((1-qsmk)*w_ate))); ATE</code></pre>
<pre><code>## # A tibble: 1 × 1
##   `(sum(qsmk * wt82 * w_ate) / sum(qsmk * w_ate)) - ...`
##                                                    &lt;dbl&gt;
## 1                                                   3.97</code></pre>
<p>We see that our estimated ATE is 3.97. This means that if someone quit smoking between 1971-1982, then they weighed approximately 3.97 kg more than someone who did not quit smoking. This does give us insight as to the causal relationship between quitting smoking and weight, but we will calculate uncertainty estimates and bootstrapped intervals in order to get an even better idea on the causal effect.</p>
<div id="uncertainty-estimates" class="section level3">
<h3>Uncertainty Estimates</h3>
<pre class="r"><code>bootstrap &lt;- bootstraps(complete_data, 1000, apparent = TRUE) %&gt;%
  mutate(df = map(splits, analysis))

fit_ipw &lt;- function(split, ...) {
  .df &lt;- analysis(split)
  # fit propensity score model
  propensity_model &lt;- glm(
    qsmk ~ age + exercise + income + sex + alcoholfreq,
    family = binomial(), 
    data = .df
  )
  # calculate inverse probability weights
  .df &lt;- propensity_model %&gt;% 
    augment(type.predict = &quot;response&quot;, data = .df) %&gt;% 
    mutate(wts = qsmk / .fitted + (1 - qsmk) / (1  - .fitted)) 
  # fit correctly bootsrapped ipw model
  lm(wt82 ~ qsmk, data = .df, weights = wts) %&gt;% 
    tidy()
}

estimate &lt;- array()
std_error &lt;- array()
for (i in 1:1000) {
    estimate[i] = fit_ipw(bootstrap$splits[[i]])[2,] %&gt;% pull(&quot;estimate&quot;)
    std_error[i] = fit_ipw(bootstrap$splits[[i]])[2,] %&gt;% pull(&quot;std.error&quot;)
}

estimates &lt;- data.frame(estimate, std_error)
quantile(estimates$estimate, probs = c(0.025, 0.975))</code></pre>
<pre><code>##     2.5%    97.5% 
## 2.146053 5.851109</code></pre>
<pre class="r"><code>quantile(estimates$std_error, probs = c(0.025, 0.975))</code></pre>
<pre><code>##      2.5%     97.5% 
## 0.7821443 0.8685548</code></pre>
<p>From the code above, we can see that a 95% confidence interval for our ATE estimate is (2.146, 5.851) with standard error (0.782, 0.869).</p>
</div>
</div>
<div id="sensitivity-analysis" class="section level2">
<h2>Sensitivity Analysis</h2>
<pre class="r"><code>smd &lt;- c(.1, .15, .2, .25, .3, .35, .4, .45, .5, .55, .6, .65, .7, .75, .8, .85, .9, .95, 1)
adjust_coef(effect = 3.88,
            smd = smd,
            outcome_association = 3.88 / smd,
            verbose = FALSE) %&gt;%
  ggplot(aes(x = smd, y = outcome_association)) +
  geom_line(color = &quot;plum4&quot;) +
  geom_point(color = &quot;plum4&quot;) +
  theme_minimal()</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-14-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>tip_lm(effect = 3.88,
        smd = 0.5)</code></pre>
<pre><code>## # A tibble: 1 × 4
##   observed_effect   smd outcome_association n_unmeasured_confounders
##             &lt;dbl&gt; &lt;dbl&gt;               &lt;dbl&gt;                    &lt;dbl&gt;
## 1            3.88   0.5                7.76                        1</code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
